### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by e-kuzminov-md** [vchkhr/mobidev-rubyInternship-mhc#21]
First of all - Great job!
Web site works and it looks solid.
:+1: for WebPack and NPM for assets.

There are couple of major architectural issues all other not so big.
Major are - complicated relations for User-Coach-Client and wrong Services usage (that should be better made as Helper method)

In details :

1) Do not need to change this

```
Gender.create!(name: 'Male')
Gender.create!(name: 'Female')
```

but heh, looks like too much to have a separate table for data that could be ENUM :)

2) Try not to store empty Helper files (like app/helpers/clients_problems_helper.rb) and Assets (app/assets/stylesheets/home.scss) if they are empty and were just generated by generator.
Store only meaningfull files with content/code.

3) Overcomplicated relations betwee Coach - User - Client
In this use-case you can have just User model and Coach model.
The most simplistic approach is to have "coach_id" in User model and Coach "has_many :user", because now user can have only one Coact attached. 

You have made Coach with user_id, and it looks like hthis wrong decision forced you to make lots of other stuff with Client model etc.
But the idea is Coach can have many simultaeous Client, whiel user cna only one Coach. So just reversing this relation in your code can simplify a lot.

Instead of ClientsTechnique you can have UsersTechnique etc.

4) Gender model looks really complicated and strange

```
class Gender < ApplicationRecord
  self.primary_key = "id"

  validates :name, presence: true, uniqueness: true

  has_many :clients, dependent: :delete_all
  has_many :coaches, dependent: :delete_all
  
  has_and_belongs_to_many :techniques
end
```

It looks like Gender is a standalone entity in our app (while it is not).
There is huge amount of code and mentions of Gender related code, I propose to remove it and refactor Gender to a simple ENUM with the same gender codes, so each entity that need to have a gender (User / Technique) would have own field to store gender code.
And it would be much simpler, would not introduce GenderController or something.

5) Services
Most of your services look like QueryObjects, they are readig datta.
For example

```
class ClientsTechniquesController < InheritedResources::Base
  def new
    @clients_technique = ClientsTechnique.new
    @clients = CoachManager::ActiveClients.call(current_user.coach)
  end

 ...

 # where
module CoachManager
  class ActiveClients < ApplicationService
    def initialize(coach)
      @coach = coach
    end
  
    def call()
      active_clients
    end
  
    private
  
    def active_clients
      clients = []
      @coach.invitations.where(status: 1).each { |invitation| clients << invitation.client }
      clients
    end
  end
end

```

This looks like to be better make with query with JOIN and place it into ActiveRecord model "scope"

to call incontroller

```
@coach.clients.from_active_clients
```
so Client model need to have "scope" that makes query finding needed data using koin to Invitations
(I proposed to place it into Clients - because ideally and logically - if you receive array of Clients in the end, it should be made in Clients model)

6) another example of unndede service is

```
module CoachManager
  class InvitationsCount < ApplicationService
    def initialize(coach)
      @coach = coach
    end
  
    def call()
      invitations_count
    end
  
    private
  
    def invitations_count
      @coach.invitations.where(status: 0).count
    end
  end
end
```

this counter could be made as a simple method in the model\

or even better - use Counter Cache feature, but default counte cache does not support conditional cache
use https://github.com/magnusvk/counter_culture  gem to have counter cache on Couch model

7) such service is better be placed in decorator or even in View Helper

```
module UserManager
  class ProfileImage < ApplicationService
    def initialize(user)
      @user = user
    end
  
    def call()
      profile_image
    end
  
    private
  
    def profile_image
      if @user.profile.image.attached?
        @user.profile.image
      else
        "https://devshift.biz/wp-content/uploads/2017/04/profile-icon-png-898.png"
      end
    end
  end
end

```

because it just decorates how image is displayed

just put it as a helper method in app/helpers/users_helper.rb or somewhere like this

8) Akso services are now used in views liek this

app/views/users/dashboard_client.html.erb

`  <p><strong><%= ClientManager::TechniquesCompletedCount.call(current_user.client) %></strong></p>`

better to use Helper method

9) Ideally ot cleanup Views from unnded files like `app/views/likes/_form.html.erb` 

it has no Form view on user interface, we do not need such autogenerated template

10) Views - Layput folder composition is unusual.
You are rendering conditional partials like
```
<%= render 'layouts/footer/footer' %>
```
in "show" templates

It's repetitive and not clean. Better to have different layput files, like "app/views/layouts/application.html.erb", just with other name.

so literally full copy of layput file for Coach/User - with own different parts that repeat on each page. 

And chnage layout by Controller directive `layuot :coach` in needed controllers. Or even on actuion render level, by passign layput name as param to `render`.

11) app/views/home/index.html.erb

Make dynamic data on this page - output real coaches, techniques and numbers from DB.
Just limit to "last(XXX)" what number is needed

12) Tests

replace assert usage like
```
   unless UserManager::ProfileImage.call(user).nil?
      assert true
    else
      assert false
    end
```
by more compact

```
   assert UserManager::ProfileImage.call(user).present?
```

just pass tested code that return boolean to `assert`

use `assert_equal` for comparison like ` if ClientManager::HoursCompleted.call(client1) == 6.5`

**Comment by vchkhr** [comment]
Discussed in PM and fixed. Please review changes in the #24
